### ISSUE TITLE
가사 리스트를 불러와서 선택하는 방법이 있으면 좋을것 같습니다.

### ISSUE THREAD

**Issue by danhk0612** [jungtaehun/alsong-lyrics-subtitle#1]
노래명, 가수명 동일한데 맨 처음 검색결과가 가사가 제대로 되어있지 않아 두번째 검색결과를 받고 싶은데
선택 기능이 없어서 아쉽네요.

**Comment by pontus-jeong** [comment]
이번 업데이트 때 여러 가사 중에 하나를 선택할 수 있게 해봤습니다. 이제 남은 건 입력 문제만 수정하면 될 것 같습니다.
